### ISSUE TITLE
Stops after 16 images

### ISSUE THREAD

**Issue by andrew-dixon** [joshbroton/gulp-tinyimg#1]
If you have a directory with more than 16 images in it, gulp-tinify stops processing the images after 16. This appears to be related to the "highWaterMark" (https://nodejs.org/api/stream.html#stream_new_stream_readable_options) and while searching for this issue I've found several other node modules that appear to have had the same problem and it appears to be related to the "through2" module somehow.

However not being a nodejs developer I'm not really sure how to fix it. 

My gulp script is very simple:

```
var gulp = require('gulp');
var tinify = require('gulp-tinify');

gulp.task('processimgs', function() {
    return gulp.src('img/src/*.jpg')
      .pipe(tinify('myKey'))
      .pipe(gulp.dest('img/dest'));
});

gulp.task('default', ['processimgs']);
```

Any guidance on a fix for this would be very welcome.

**Comment by andrew-dixon** [comment]
Bit more digging leads me to believe it is related to the `through2-concurrent` being used. If I add the option `{maxConcurrency: 20}`, I get 20 images processed instead and the default for `maxConcurrency` is 16. I've tried changing `through2-concurrent` to `through2` instead, but then I only get 1 image processed.

**Comment by joshbroton** [comment]
That's a completely unexpected problem. I think I know how to fix it. I'll tackle it this weekend.

**Comment by andrew-dixon** [comment]
@joshbroton - I've managed to fix the issue (learning lots about nodejs as I went). I've submitted a pull request with my changes #2.
